[package]
name = "rustpals"
version = "0.1.0"
authors = ["Theron Spiegl <tspiegl@gmail.com>"]
edition = "2018"

[dependencies]
aes = "0.1.0"
block-modes = "0.1.0"
rand = "0.5"
sha-1 = "0.8.1"
md4 = "0.9.0"
